In [1]:
import numpy as np

In [3]:
a = np.empty((2,3), dtype=np.int8)
a

array([[120, 117,   0],
       [  0, -24,   3]], dtype=int8)

In [4]:
p = np.array([[1,2,3],[4,5,6]])
a = np.empty_like(p)
a

array([[1302944064,        560,          0],
       [         0,          1,    6029353]])

In [5]:
a = np.eye(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [6]:
a = np.eye(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
a = np.identity(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
a = np.ones((2,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
a = np.zeros((2,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
a = np.full((2,3),7)
a

array([[7, 7, 7],
       [7, 7, 7]])

In [14]:
a = np.arange(10,100,2)
a

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])