In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [6]:
a = np.array([1,2,3])
type(a)

numpy.ndarray

In [7]:
a.ndim

1

In [8]:
a = np.array([
    [1,2,3],
    [4,5,6]
])
a.shape

(2, 3)

In [9]:
a = np.array([1,2,3])
a.dtype

dtype('int32')

In [12]:
a = np.array([1,2,3] , dtype=np.uint8)
a.dtype

dtype('uint8')

In [13]:
a = np.array([
    [1,2,3],
    [4,5,6]
])
a.size

6

In [14]:
a = np.array([
    [1,2,3],
    [4,5,6]
])
a.shape

(2, 3)

In [15]:
a.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [16]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
b = np.array ([7,8,9])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
c = np.array ([[10],[11]])
np.hstack((a,c))

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11]])

In [21]:
k=np.array([[2],[3],[4]])
k

array([[2],
       [3],
       [4]])

In [22]:
a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [23]:
a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
np.vsplit(a,3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [24]:
np.hsplit(a,3)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [25]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[  1, 100,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [30]:
a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
b = a.copy()
b[0,1]=100
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
c = a.view()
c[0,1]=100
a

array([[  1, 100,   3],
       [  4,   5,   6],
       [  7,   8,   9]])