In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3]])
b = np.array([[1,2,5]])
np.array_equal(a,b)

False

In [3]:
a == b

array([[ True,  True, False]])

In [4]:
a = np.array([[1,2,3]])
np.sum (a)

6

In [5]:
a = np.array([
             [1,2,3],
             [4,5,6]
             ])
a.sum(axis=0)

array([5, 7, 9])

In [6]:
a = np.array([
             [1,2,3],
             [4,5,6]
             ])
a.sum(axis=1)

array([ 6, 15])