In [1]:
import numpy as np

In [4]:
a = np.array([5, 1, 8, 4, 2])
a.sort()

a

array([1, 2, 4, 5, 8])

In [8]:
a = np.array([[5, 1, 8],
              [2, 6, 3]])

a.sort(axis=0)
a

array([[2, 1, 3],
       [5, 6, 8]])

In [9]:
lastName = ('Hojjati' , 'Asadi' , 'Hojjati')
firstName = ('Kiana' , 'Arghavan' , 'Diba')

np.lexsort((firstName , lastName))

array([1, 2, 0], dtype=int64)

In [10]:
a = np.array ([4, 1, 6])
np.argsort(a)

array([1, 0, 2], dtype=int64)

In [13]:
x = np.array([6,4,7,2,1])
x.sort()
np.searchsorted(x,5)

3

In [14]:
a = np.array([1, 4, 5, 100])
np.argmax(a)

3

In [15]:
a = np.array([1, 4, 5, 100])
np.argmin(a)

0

In [17]:
a = np.array([4, 9, 1, 2, 3, 0])
np.extract(np.mod(a, 3)==0, a)

array([9, 3, 0])

In [18]:
a = np.array([4, 9, 1, 2, 3, 0])
np.count_nonzero(a)

5